import presentations from '../../content/presentations.json';
import blog from '../../content/blog.json';
import qiita from '../../content/qiita.json';
import zenn from '../../content/zenn.json';
import labels from '../../content/resources.json';
const base='/official';
type Post={title:string;date:string;url:string};
const qiitaPosts=qiita.posts as Post[]; const zennPosts=zenn.posts as Post[];
const PostList=({posts}:{posts:Post[]})=><>{posts.length?posts.map(item=><a className="resource-card" href={item.url} target="_blank" key={item.url}><span>{item.date}</span><strong>{item.title}</strong><b>↗</b></a>):<p className="lead">公開後に自動で表示されます。</p>}</>;
export default function Resources(){return <main className="inner-page"><a className="brand" href={base+'/' }><span>T</span> Taisei / PORTFOLIO</a><p className="section-kicker">RESOURCES</p><h1>{labels.pageTitle}</h1><section className="resource-section"><h2>{labels.presentationsHeading}</h2><p className="lead">{labels.presentationsDescription}</p>{presentations.presentations.map(item=>{const link=item.file||item.url;return <article className="presentation" key={item.title}><div><span>{item.event}</span><h3>{item.title}</h3><p>{item.description}</p><a className="text-link" href={link} target="_blank">資料を開く ↗</a></div>{item.file&&<iframe title={item.title} src={item.file} loading="lazy"/>}</article>})}</section><section className="resource-section"><h2>{labels.blogHeading}</h2><PostList posts={blog.posts}/></section><section className="resource-section"><h2>{labels.qiitaHeading}</h2><PostList posts={qiitaPosts}/></section><section className="resource-section"><h2>{labels.zennHeading}</h2><PostList posts={zennPosts}/></section><footer><div className="footer-brand"><span>T</span><p>Taisei / PORTFOLIO</p></div><div className="footer-links"><div><b>NAVIGATE</b><a href={base+'/about/'}>About</a><a href={base+'/works/'}>Works</a><a href={base+'/resources/'}>Resources</a><a href={base+'/contact/'}>Contact</a></div></div><small>© 2026 TAISEI KAWAKAMI. ALL RIGHTS RESERVED.</small></footer></main>}
